---
theme: jekyll-theme-leap-day
site:
  title: SPb Python
  description: Сообщество Python-программистов Санкт-Петербурга
gems:
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-titles-from-headings
...